mode: "HttpServerSingle"
http_server_address: "127.0.0.1"
http_server_port: "3333"

available_memory: 20480
benchmarking: true

heuristics:
  two_middle_pawns_weight: 3
  castling_weight: 4
  knight_outpost_weight: 2
  development_weight: 4
  mobility_weight: 4
