package ChessNetwork.Pieces;

import ChessNetwork.MoveGenerator;

import java.util.ArrayList;

import static ChessNetwork.ChessboardHelper.*;

public class Knight {

    public static Move[] getMoves(int x, int y, int color, MoveGenerator moveGenerator) {
        long[] squares = {
                1L << ((y - 2) * 8 + x + 1),
                1L << ((y - 2) * 8 + x - 1),
                1L << ((y + 2) * 8 + x + 1),
                1L << ((y + 2) * 8 + x - 1),
                1L << ((y - 1) * 8 + x + 2),
                1L << ((y + 1) * 8 + x + 2),
                1L << ((y - 1) * 8 + x - 2),
                1L << ((y + 1) * 8 + x - 2),
        };
        long whitePieces = moveGenerator.getWhitePieces();
        long blackPieces = moveGenerator.getBlackPieces();
        ArrayList<Move> moves = new ArrayList<>();
        //magic generated by chatgpt
        for (int i = 0; i < 8; i++) {
            long s = squares[i];
            int dx = ((i % 4) < 2 ? 1 : -1) * ((i / 4) * 2 - 1);
            int dy = ((i % 4) >= 2 ? 1 : -1) * ((i / 4) * 2 - 1);
            if ((color == 1 && (whitePieces & s) == 0) || (color == -1 && (blackPieces & s) == 0)) {
                int newX = x + dx;
                int newY = y + dy;
                if (newX >= 0 && newX < 8 && newY >= 0 && newY < 8) {
                    if ((color == 1 && (blackPieces & s) != 0) || (color == -1 && (whitePieces & s) != 0)) {
                        moves.add(new Move(x, y, newX, newY, color * KNIGHT));
                    } else {
                        moves.add(new Move(x, y, newX, newY, color));
                    }
                }
            }
        }
        return moves.toArray(new Move[0]);
    }

}